<<<<<<< SEARCH
name: restaurant
description: Fraved Restaurante Copyright 2022

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.3.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.4.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  flutter_secure_storage: ^8.0.0
  http: ^0.13.5
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  image_picker: ^0.8.7+4
  form_field_validator: ^1.1.0
  android_intent_plus: ^3.1.9
  shimmer: ^2.0.0
  carousel_slider: ^4.1.1
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.5
  permission_handler: ^10.2.0
  geocoding: ^2.1.0
  intl: ^0.18.1
  polyline_do: ^0.1.0
  url_launcher: ^6.1.10
  socket_io_client: 1.0.2
  firebase_messaging: ^14.4.1
  firebase_core: ^2.10.0
  flutter_local_notifications: ^14.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - Assets/
    - Assets/Logo/
    - Assets/svg/
=======
name: restaurant
description: Fraved Restaurante Copyright 2022

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.5.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^8.0.0
  http: ^1.1.0
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  image_picker: ^1.0.2
  form_field_validator: ^1.1.0
  android_intent_plus: ^4.0.2
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  geolocator: ^10.0.1
  google_maps_flutter: ^2.5.0
  permission_handler: ^10.4.3
  geocoding: ^2.1.0
  intl: ^0.18.1
  polyline_do: ^1.0.0
  url_launcher: ^6.1.12
  socket_io_client: ^2.0.3
  firebase_messaging: ^14.6.5
  firebase_core: ^2.15.0
  flutter_local_notifications: ^15.1.0+1
  firebase_auth: ^4.7.0
  cloud_firestore: ^4.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:

  uses-material-design: true

  assets:
    - Assets/
    - Assets/Logo/
    - Assets/svg/
>>>>>>> REPLACE
